name: Docker Image CI
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      registry_url:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.3.0
      - name: "Docker Setup Buildx"
        uses: docker/setup-buildx-action@v2.4.0
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username}}
          password: ${{ secrets.registry_ password}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ secrets.registry_url }}/${{inputs.image_name}}:${{inputs.tag}}
